version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "MorrisHannessen" 
    assignees:
      - "MorrisHannessen"
    labels:
      - "dependencies"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "MorrisHannessen"
    assignees:
      - "MorrisHannessen"
    labels:
      - "docker"
      - "dependencies"
      - "automated"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "MorrisHannessen"
    assignees:
      - "MorrisHannessen"
    labels:
      - "github-actions"
      - "dependencies"
      - "automated" 