version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: babbly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: babbly_user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - babbly-network

  user-service:
    build:
      context: .
    container_name: babbly-user-service
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=babbly_user_service;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks:
      - babbly-network

networks:
  babbly-network:
    driver: bridge

volumes:
  postgres-data: 