version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: babbly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: babbly_user_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - babbly-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: babbly-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - babbly-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: babbly-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - babbly-network

  user-service:
    build:
      context: .
    container_name: babbly-user-service
    depends_on:
      - postgres
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=babbly_user_service;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "5000:80"
    networks:
      - babbly-network

networks:
  babbly-network:
    driver: bridge

volumes:
  postgres-data: 