apiVersion: batch/v1
kind: Job
metadata:
  name: babbly-user-db-migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: ${DOCKER_REGISTRY}/babbly-user-service:latest
          command:
            [
              "dotnet",
              "ef",
              "database",
              "update",
              "--project",
              "babbly-user-service",
            ]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: user-service-connection-string
