apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  labels:
    app: user-service
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 