name: User Service CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of SonarCloud analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/*.test.js,**/*.spec.js
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Restore dependencies
        run: dotnet restore babbly-user-service.sln

      - name: Build
        run: dotnet build babbly-user-service.sln --no-restore

      - name: Test
        run: dotnet test babbly-user-service.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      # Uncomment when tests are added
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     directory: ./coverage

  docker-build:
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    needs: [code-quality, backend-tests]
    if: |
      always() &&
      (needs.code-quality.result == 'success' || needs.code-quality.result == 'skipped') &&
      (needs.backend-tests.result == 'success' || needs.backend-tests.result == 'skipped')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "ASPNETCORE_ENVIRONMENT=Development" > .env
          echo "DB_CONNECTION_STRING=Host=db;Database=babbly-users;Username=babbly_user;Password=babbly_password;" >> .env

      - name: Build and push User Service
        run: |
          # Always build the image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:${{ github.sha }} .

          # Only push to DockerHub on main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:${{ github.sha }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:latest
          fi

      - name: Check user service health
        run: |
          docker run --rm -d -p 5001:80 --name test-user-service ${{ secrets.DOCKERHUB_USERNAME }}/babbly-user-service:${{ github.sha }}
          sleep 10
          curl -f http://localhost:5001/api/health || exit 1
          docker stop test-user-service

  deploy:
    name: Deploy
    needs: [docker-build]
    if: |
      always() &&
      github.ref == 'refs/heads/main' &&
      needs.docker-build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install GKE Auth Plugin
        run: |
          # Add the Cloud SDK distribution URI as a package source
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

          # Import the Google Cloud public key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

          # Update and install the plugin
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to GKE
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace babbly --dry-run=client -o yaml | kubectl apply -f -

          # Apply secrets first
          kubectl apply -f k8s/secrets.yaml -n babbly

          # Apply database deployment (always needed)
          kubectl apply -f k8s/postgres-deployment.yaml -n babbly

          # Deploy user service
          echo "Deploying user service..."
          kubectl apply -f k8s/user-service-deployment.yaml -n babbly
          kubectl wait --for=condition=available deployment/babbly-user-service -n babbly --timeout=300s

          # Wait for database to be ready
          kubectl wait --for=condition=available statefulset/postgres -n babbly --timeout=300s
